version: build.{build}
image: Visual Studio 2022

branches:
  except:
    - /v\d+\.\d+\.\d+/
skip_commits:
  files:
    - docs/
    - misc/
    - README.md
    - LICENSE
    - CODE_OF_CONDUCT.md
    - CONTRIBUTING.md
    - SECURITY.md

init:
- cmd: git config --global core.autocrlf true
- cmd: setx IGNORE_NORMALISATION_GIT_HEAD_MOVE "1"
- cmd: RefreshEnv.cmd
- pwsh: Write-Host "Target branch is '$($env:APPVEYOR_REPO_BRANCH)'"

before_build:
- cmd: gitversion /output buildserver /verbosity Minimal
- pwsh: Write-Host "Building PocketCsvReader version $($env:GitVersion_SemVer)"
- pwsh: |
    . "$env:APPVEYOR_BUILD_FOLDER\github.ps1"
    if (($env:APPVEYOR_REPO_BRANCH -eq "main") -and ($null -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)) {
      $context = [PSCustomObject] @{
        Id = $env:APPVEYOR_REPO_COMMIT
        Owner = ($env:APPVEYOR_REPO_NAME -Split '/')[0]
        Repository = ($env:APPVEYOR_REPO_NAME -Split '/')[1]
        SecretToken = $env:github_access_token
      }
      foreach($id in ($context | Get-Commit-Associated-Pull-Requests)) {
        $context.Id = $id
        $context | Set-Pull-Request-Expected-Labels -Config '.github\conventional_commits_labels.json'
      }
    } else {
        Write-Host 'Not a merge on main built on appveyor. Skipping mapping conventional commits and labels.'
    }

build_script:
  #- dotnet --info
  - dotnet build PocketCsvReader.sln -p:version="%GitVersion_SemVer%" -c Release /p:ContinuousIntegrationBuild=true --nologo

test_script:
- pwsh: |
    $ErrorActionPreference = "Stop"
    dotnet test PocketCsvReader.Testing -c Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Threshold=10 /p:ThresholdType=line /p:CoverletOutput=../.coverage/coverage.DubUrl.xml --test-adapter-path:. --logger:Appveyor --no-build --nologo
    $globalTestResult = $LastExitCode
    if($globalTestResult -ne 0) { $host.SetShouldExit($globalTestResult) }

after_build:
- ps: >-
    $nuget_version = "$env:GitVersion_NuGetVersionV2"

    .\.packages\package-PocketCsvReader.ps1 $nuget_version

artifacts:
- path: PocketCsvReader\bin\Debug
  name: PocketCsvReader
- path: .nupkg\PocketCsvReader.*.nupkg
  name: Nuget packages
deploy:
- provider: NuGet
  api_key:
    secure: WFF9dTQz6X6KCEaTxeLnHjZlt7YHSnRrEhc/RmnEpJSXAbeWrZXqVZFTph5Bk8yg
  on:
    branch: develop
- provider: NuGet
  api_key:
    secure: WFF9dTQz6X6KCEaTxeLnHjZlt7YHSnRrEhc/RmnEpJSXAbeWrZXqVZFTph5Bk8yg
  on:
    APPVEYOR_REPO_TAG: true
- provider: NuGet
  server: https://nuget.pkg.github.com/Seddryck/index.json
  username: Seddryck
  api_key:
    secure: vmXLz/XAhXz3eNJPtg5mP78yhliNVtPy4ieiwuGD9Ym47b5CvdXLT0B4tr/VHDoX
  on:
    branch: develop
- provider: NuGet
  server: https://nuget.pkg.github.com/Seddryck/index.json
  username: Seddryck
  api_key:
    secure: vmXLz/XAhXz3eNJPtg5mP78yhliNVtPy4ieiwuGD9Ym47b5CvdXLT0B4tr/VHDoX
  on:
    APPVEYOR_REPO_TAG: true
